apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-auth
  template:
    metadata:
      labels:
        app: app-auth
    spec:
      containers:
        - name: cont-auth
          image: azold6/kub-demo-auth:latest